export { NavigatePage } from './navigate'
export { LoginPage } from './login'
export { RegisterPage } from './register'
export { TestPage } from './test'
export { MainPage } from './main'
export { UserPage } from './user'
export { ErrorPage } from './error'
